[general]
caption_extension = '.txt'

[[datasets]]
resolution = 512
batch_size = 2
enable_bucket = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/peescat/diaper'
    color_aug = false
    num_repeats = 20