[general]
shuffle_caption = true
caption_extension = '.txt'
keep_tokens = 2

[[datasets]]
resolution = 512
batch_size = 2
keep_tokens = 2
enable_bucket = true


    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/gagagabad'
    color_aug = false
    num_repeats = 2
    class_tokens = 'gagagabad person'
    
    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/person'
    color_aug = false
    class_tokens = 'person'
    num_repeats = 8
    is_reg = true