[general]
caption_extension = '.txt'

[[datasets]]
resolution = 512
batch_size = 4
enable_bucket = true
color_aug = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa/kaname'
    num_repeats = 20