[general]
shuffle_caption = true
caption_extension = '.txt'
keep_tokens = 2

[[datasets]]
resolution = 512
batch_size = 4
keep_tokens = 2
enable_bucket = true


    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa/reina'
    color_aug = false
    num_repeats = 20
    shuffle_caption = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa/makina'
    color_aug = false
    num_repeats = 20
    shuffle_caption = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa/kaname'
    color_aug = false
    num_repeats = 20
    shuffle_caption = true