[general]
shuffle_caption = true
caption_extension = '.txt'
keep_tokens = 2

[[datasets]]
resolution = 512
batch_size = 1
keep_tokens = 2
enable_bucket = true
color_aug = false


    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa/reina'
    num_repeats = 1
    shuffle_caption = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa/makina'
    num_repeats = 1
    shuffle_caption = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa/kaname'
    num_repeats = 1
    shuffle_caption = true