[general]
shuffle_caption = true
caption_extension = '.txt'
keep_tokens = 2

[[datasets]]
resolution = 512
batch_size = 4
keep_tokens = 2
enable_bucket = true


    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa_maruzen/reina_maruzen/reina'
    color_aug = false
    num_repeats = 10
    shuffle_caption = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa_maruzen/makina_maruzen/makina'
    color_aug = false
    num_repeats = 10
    shuffle_caption = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa_maruzen/kaname_maruzen/kaname'
    color_aug = false
    num_repeats = 10
    shuffle_caption = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa_maruzen/reina_maruzen/reina_strahl'
    color_aug = false
    num_repeats = 10
    shuffle_caption = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa_maruzen/makina_maruzen/makina_strahl'
    color_aug = false
    num_repeats = 10
    shuffle_caption = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa_maruzen/kaname_maruzen/kaname_strahl'
    color_aug = false
    num_repeats = 10
    shuffle_caption = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/girl'
    color_aug = false
    num_repeats = 5
    is_reg = true