[general]
caption_extension = '.txt'
keep_tokens = 2

[[datasets]]
resolution = 512
batch_size = 4
enable_bucket = true
color_aug = false


    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa/reina'
    num_repeats = 1

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa/makina'
    num_repeats = 1

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa/kaname'
    num_repeats = 1