[general]
caption_extension = '.txt'

[[datasets]]
resolution = 768
batch_size = 4
enable_bucket = true
color_aug = false


    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/kyawawa/reina'
    num_repeats = 20