[general]
shuffle_caption = true
caption_extension = '.txt'
keep_tokens = 2

[[datasets]]
resolution = 512
batch_size = 4
keep_tokens = 2
enable_bucket = true


    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/reina'
    color_aug = false
    num_repeats = 8
    class_tokens = ' reina 1girl'
    
    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/girl'
    color_aug = false
    class_tokens = '1girl'
    num_repeats = 8
    is_reg = true