[general]
caption_extension = '.txt'

[[datasets]]
resolution = 512
batch_size = 4
enable_bucket = true

    [[datasets.subsets]]
    image_dir = '/content/kohya-mydatasets/peescat/diaper'
    num_repeats = 8